### ISSUE TITLE
Error: version mismatch when installing pylokit in Ubuntu 16

### ISSUE THREAD

**Issue by pcdinh** [xrmx/pylokit#11]
```
ubuntu@ip-172-31-6-194:/tmp/pylokit$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Install pylokit using pip

```
pip install pylokit
```

Sample code:

```
lo_path = "/usr/lib/libreoffice/program"
with Office(lo_path) as lo:
    with lo.documentLoad(original_file_path) as doc:
        doc.saveAs(pdf_file_path)
```

Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/src/pylokit/pylokit/lokit.py", line 97, in __init__
    ffi = FFI()
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.5.2 != 1.8.3
```

This error can be only resolved by installing pylokit from source

```
git clone https://github.com/xrmx/pylokit.git
sudo python setup.py install
```

**Comment by xrmx** [comment]
It looks like your system cffi is broken. Anyway is recommended to install python packages on a virtualenv so you don't mess with the distro packages. I don't think there's something we can fix here, closing.
