### ISSUE TITLE
Unknown load failure

### ISSUE THREAD

**Issue by BackSeat** [xrmx/pylokit#13]
What's the best way to diagnose this problem?

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/templated_docs/__init__.py", line 95, in _convert_subprocess
    with lo.documentLoad(filename) as doc:
  File "/usr/local/lib/python3.4/dist-packages/pylokit/lokit.py", line 115, in documentLoad
    raise LoKitImportError(self.getError())
pylokit.lokit.LoKitImportError: b'unknown load failure'
```

**Comment by xrmx** [comment]
Ask the libreoffice developers what that means :)

**Comment by BackSeat** [comment]
Is there anything I can do to try to resolve this, or is that the only way forwards?
